# Generated by Django 2.1 on 2018-08-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20180828_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.Currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Product', verbose_name='Товар'),
        ),
    ]
