# Generated by Django 2.1 on 2018-08-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20180828_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['product'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Currency', verbose_name='Валюта'),
        ),
    ]
